# xpython-quarto
Debug repo for xeus-python RuntimeError

clone repo
```bash
git clone https://github.com/laguill/xpython-quarto.git
```

init uv project

```bash
uv sync
```
Try to preview file

```bash
uv run quarto preview test.qmd
```
